/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unab.edu.clase1.parking_service;

import com.unab.edu.DAO.ClsEstacionamiento;
import com.unab.edu.DAO.ClsJoinParkingNivel;
import com.unab.edu.Entidades.Estacionamiento;
import com.unab.edu.Entidades.Parking;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class frmEstacionamiento extends javax.swing.JPanel {

    /**
     * Creates new form frmEstacionamiento
     */
    public frmEstacionamiento() {
        initComponents();      
        MostrarTabla();
        String Titulos[] = {"ID PARKING", "UBICACION", "ID NIVEL"};
        DefaultTableModel df = new DefaultTableModel(null, Titulos);
        ClsJoinParkingNivel ClsJoinPN = new ClsJoinParkingNivel();
        var MostrarJoinParkingNivel = ClsJoinPN.MostrarJoinParkingNivel();
        String Filas[] = new String[3];

        for (var iterador : MostrarJoinParkingNivel) {

            Filas[0] = String.valueOf(iterador.getId_parking());
            Filas[1] = iterador.getUbicacion();
            Filas[2] = String.valueOf(iterador.getId_nivel());
            df.addRow(Filas);
        }

        tbParkinsYEstacionamientos.setModel(df);

    }
    
    void MostrarTabla ()
    {
    
        String TITULOS [] = {"ID ESTACIONAMIENTO","ID NIVEL","ID PARQUEO","ESTADO"};
        DefaultTableModel ModeloTabla = new DefaultTableModel(null, TITULOS);
        ClsEstacionamiento claseEstacionamiento = new ClsEstacionamiento();
        ArrayList <Estacionamiento> Estacionamientos =  claseEstacionamiento.MostrarEstacionamientos();
        String filas [] = new String [5];
        for (var IterarDatos : Estacionamientos){
        
        filas[0] = String.valueOf(IterarDatos.getId_estacionamiento());
        filas[1] = String.valueOf(IterarDatos.getId_nivel());
        filas[2] = String.valueOf(IterarDatos.getId_parqueo());
        filas[3] = String.valueOf(IterarDatos.getEstado());
        
        
        ModeloTabla.addRow(filas);
            
        }
    
        tbEstacionamientos.setModel(ModeloTabla);
    }
    
   
    
    void Limpiar (){
        
      txtId.setText("");
      txtNivel.setText("");
      txtParqueo.setText("");      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbp_mostrar = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbParkinsYEstacionamientos = new javax.swing.JTable();
        txtParqueo = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNivel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbEstacionamientos = new javax.swing.JTable();

        btnEliminar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tbParkinsYEstacionamientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbParkinsYEstacionamientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbParkinsYEstacionamientosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbParkinsYEstacionamientos);

        txtParqueo.setEnabled(false);

        txtId.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Numero");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Nivel Asigando");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Parqueo Asignado");

        txtNivel.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("CRUD ESTACIONAMIENTO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(txtNivel)
                        .addComponent(txtParqueo, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(292, 292, 292))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtParqueo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        tbp_mostrar.addTab("Opciones Avanzadas", jPanel1);

        tbEstacionamientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbEstacionamientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEstacionamientosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbEstacionamientos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        tbp_mostrar.addTab("Mostrar Estacionamientos", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbp_mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbp_mostrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbParkinsYEstacionamientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbParkinsYEstacionamientosMouseClicked
        tbp_mostrar.setSelectedIndex(tbp_mostrar.indexOfComponent(jPanel1));

        int fila = tbParkinsYEstacionamientos.getSelectedRow();

        String IDParking = String.valueOf(tbParkinsYEstacionamientos.getValueAt(fila, 0)); 
        String IdNivel =String.valueOf(tbParkinsYEstacionamientos.getValueAt(fila, 2)); 
        
        txtParqueo.setText(IDParking);
        txtNivel.setText(IdNivel);
    }//GEN-LAST:event_tbParkinsYEstacionamientosMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (txtId.getText().equals("")) {
            if (txtNivel.getText() != "" && txtParqueo.getText() != "") {

                ClsEstacionamiento Estacionamientos = new ClsEstacionamiento();
                Estacionamiento Estacionamiento = new Estacionamiento();
                Estacionamiento.setId_nivel(Integer.parseInt(txtNivel.getText()));
                Estacionamiento.setId_parqueo(Integer.parseInt(txtParqueo.getText()));
                Estacionamientos.GuardarEstacionamiento(Estacionamiento);
                MostrarTabla();
                Limpiar();
                
            } else {

                JOptionPane.showMessageDialog(null, "Hay campos Vacios");
            }
        }
        else if (txtId.getText() != ""){
            
            if (txtNivel.getText() != "" && txtParqueo.getText() != "") {
           
                ClsEstacionamiento Estacionamientos = new ClsEstacionamiento();
                Estacionamiento Estacionamiento = new Estacionamiento();
                Estacionamiento.setId_estacionamiento(Integer.parseInt(txtId.getText()));
                Estacionamiento.setId_nivel(Integer.parseInt(txtNivel.getText()));
                Estacionamiento.setId_parqueo(Integer.parseInt(txtParqueo.getText()));
                Estacionamientos.ActualiarEstacionamiento(Estacionamiento);
                MostrarTabla();
                Limpiar();
           }
        else{
            
            JOptionPane.showMessageDialog(null, "Hay campos Vacios");
        }
            
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (txtNivel.getText() != "" && txtParqueo.getText() != "" && txtId.getText() != "") {
                
            ClsEstacionamiento Estacionamientos = new ClsEstacionamiento();
            Estacionamiento Estacionamiento = new Estacionamiento();
            Estacionamiento.setId_estacionamiento(Integer.parseInt(txtId.getText()));
            Estacionamientos.EliminarEstacionamiento(Estacionamiento);
            MostrarTabla();
            Limpiar();
        }
        else{
            
            JOptionPane.showMessageDialog(null, "Hay campos Vacios");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tbEstacionamientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEstacionamientosMouseClicked
         tbp_mostrar.setSelectedIndex(tbp_mostrar.indexOfComponent(jPanel1));

        int fila = tbEstacionamientos.getSelectedRow();

        String ID = String.valueOf(tbEstacionamientos.getValueAt(fila, 0)); 
        String IDParking = String.valueOf(tbEstacionamientos.getValueAt(fila, 2)); 
        String IdNivel =String.valueOf(tbEstacionamientos.getValueAt(fila, 1)); 
        
        txtId.setText(ID);
        txtParqueo.setText(IDParking);
        txtNivel.setText(IdNivel);
    }//GEN-LAST:event_tbEstacionamientosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbEstacionamientos;
    private javax.swing.JTable tbParkinsYEstacionamientos;
    private javax.swing.JTabbedPane tbp_mostrar;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNivel;
    private javax.swing.JTextField txtParqueo;
    // End of variables declaration//GEN-END:variables
}
