/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unab.edu.clase1.parking_service;

import com.unab.edu.DAO.ClsAutomovil;
import com.unab.edu.DAO.ClsEstacionamiento;
import com.unab.edu.DAO.ClsParking;
import com.unab.edu.Entidades.Automovil;
import com.unab.edu.Entidades.Estacionamiento;
import com.unab.edu.Entidades.Parking;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class frmIngresoAutos extends javax.swing.JPanel {

    /**
     * Creates new form frmIngresoAutos
     */
    public frmIngresoAutos() {
        initComponents();
        DisplayMember();
        MostrarTabla();
    }
    
    void Limpiar(){
        
        
    }
    
    void MostrarTabla ()
    {
    
        String TITULOS[] = {"NUM_CORRELATIVO", "ESTADO"};
        DefaultTableModel ModeloTabla = new DefaultTableModel(null, TITULOS);
        ClsEstacionamiento claseEstacionamiento = new ClsEstacionamiento();
        ArrayList<Estacionamiento> cuenta = claseEstacionamiento.MostrarEstacionamientos();
        String filas[] = new String[5];
        for (var IterarDatos : cuenta) {

            filas[0] = String.valueOf(IterarDatos.getId_estacionamiento());

            String Estado = String.valueOf(IterarDatos.getEstado());
            int tipo = Integer.parseInt(Estado);

            if (tipo == 1) {
                filas[1] = "Activo";
            }            

            ModeloTabla.addRow(filas);

        }

        tbEstacionamientos.setModel(ModeloTabla);
    }
    
    String Valuemember[];
    int contador = 0;
    
    void DisplayMember(){
        
        DefaultComboBoxModel cbdefault = new DefaultComboBoxModel();
        ClsParking claseParking = new ClsParking();
        ArrayList<Parking> Parkings = claseParking.MostrarParkings();
        Valuemember = new String [Parkings.size()];
        String Filas[] = new String[5];
        for (var iterarDatos : Parkings){
            Filas[0] = String.valueOf(iterarDatos.getId_parking());
            Filas[1] = iterarDatos.getUbicacion();
            Valuemember [contador] = Filas[0];
            cbdefault.addElement(Filas[1]);
            contador++;
                        
        }
      
        cmbParking.setModel(cbdefault);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbp_mostrar = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        cmbParking = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtestacionamiento = new javax.swing.JTextField();
        txtplaca = new javax.swing.JTextField();
        txtcolor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEstacionamientos = new javax.swing.JTable();
        btnIngresar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        cmbParking.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbParking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbParkingMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Placa");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("color");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("parqueo");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("numero de estacionamiento");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("INGRESAR AUTO AL ESTACIONAMIENTO");

        tbEstacionamientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbEstacionamientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEstacionamientosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbEstacionamientos);

        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbParking, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtplaca, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(txtestacionamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtplaca, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtestacionamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cmbParking, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        tbp_mostrar.addTab("tab1", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbp_mostrar, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbp_mostrar, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbEstacionamientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEstacionamientosMouseClicked
        tbp_mostrar.setSelectedIndex(tbp_mostrar.indexOfComponent(jPanel1));

        int fila = tbEstacionamientos.getSelectedRow();

        String ID = String.valueOf(tbEstacionamientos.getValueAt(fila, 0));       
        
        txtestacionamiento.setText(ID);
    }//GEN-LAST:event_tbEstacionamientosMouseClicked

    private void cmbParkingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbParkingMouseClicked
              
    }//GEN-LAST:event_cmbParkingMouseClicked

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
//        if (txtcolor.getText() != "" && txtestacionamiento.getText() != "" && txtplaca.getText() != "" ) {
//
//            ClsAutomovil Automoviles = new ClsAutomovil();
//            Automovil Automovil = new Automovil();
//            Automovil.setPlaca(txtplaca.getText());
//            Automovil.setColor(txtcolor.getText());
//            Automovil.setId_parqueo(PROPERTIES);
//            Estudiante.setMatricula(Integer.parseInt(txtMatricula.getText()));
//            Estudiante.setIdPersona(Integer.parseInt(txtIdPersona.getText()));
//            Estudiante.setPASS(txtPass.getText());
//            Estudiante.setUSU(txtUsuario.getText());
//            Estudiante.setNIE(txtNIE.getText());
//            Estudiantes.AgregarEstudiante(Estudiante);
//            MostrarTablaPersona();
//            Limpiar();
//        } else{
//            
//            JOptionPane.showMessageDialog(null, "Hay campos Vacios");
//        }
    }//GEN-LAST:event_btnIngresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JComboBox<String> cmbParking;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbEstacionamientos;
    private javax.swing.JTabbedPane tbp_mostrar;
    private javax.swing.JTextField txtcolor;
    private javax.swing.JTextField txtestacionamiento;
    private javax.swing.JTextField txtplaca;
    // End of variables declaration//GEN-END:variables
}
